#!/bin/bash

LIKEPATH="./sodapop/etc"
LIKES='4U1700-377,Cyg_X-2,SMC_X-1,Cen_X-3,XTE_J2123-058,4U_1822-37,OAO_1657-415,J013236.7+303228,Vela_X-1,4U1538-522,LMC_X-4,Her_X-1,2S_0921-630,EXO_1722-363,SAXJ1802.7-2017,XTEJ1855-026,J0453+1559,J0453+1559_comp.,J1906+0746,J190+0746_comp.,B1534+12,B1534+12_comp.,B1913+16,B1913+16_comp.,B2127+11C,B2127+11C_comp.,J0737-3039A,J0737-3039B,J1756-2251,J1756-2251_comp.,J1807-2500B,J1807-2500B_comp.,J2045+3633,J2053+4650,J1713+0747,B1855+09,J0751+1807,J1141-6545,J1738+0333,J1614-2230,J0348+0432,J2222-0137,J2234+0611,J1949+3106,J1012+5307,J0437+4715,J1909-3744,J1802-2124,J1911-5958A,J2043+1711,J0337+1715,J1946+3417,J1918-0642,J1600-3053,J0045-7319,J1023+0038,J1903+0327,J0740+6602,J1913+1102,J0024-7204H,J0514-4002A,J0621+1002,B1516+02B,J1748-2021B,J1748-2446I,J1748-2446J,B1802-07,J1824-2452C,B2303+46,J1750-37A,B1957+20,J1311-3430,J1740-5350,J1816+4510,J1723-2837'
CLASSES='psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr,psr'
LIKESETS="A"
MINMMAXS="1.7"
NSBHBETA="0."

POPMODELS="unif_m1m2,unif_m1m2_qpair,power_m1m2,power_m1m2_qpair,bimodcut_m1m2,bimodcut_m1m2_qpair"
POPSTARTS="mmin,mmax+flatmmin_mmax,1.,1.4;mmin,mmax+flatmmin_mmax,1.,1.4 beta+flat,0.,4.;alpha+flat,-4.,0. mmin,mmax+flatmmin_mmax,1.,1.4;alpha+flat,-4.,0. mmin,mmax+flatmmin_mmax,1.,1.4 beta+flat,0.,4.;mmin,mmax,mu1,mu2+flatmminmu1mu2_mmax,1.,1.4,1.,2.,1.,2. sigma1+flat,0.01,2. sigma2+flat,0.01,2. w+flat,0.,1.;mmin,mmax,mu1,mu2+flatmminmu1mu2_mmax,1.,1.4,1.,2.,1.,2. sigma1+flat,0.01,2. sigma2+flat,0.01,2. w+flat,0.,1. beta+flat,0.,4."
POPPRIORS="mmin,mmax+flatmmin_mmax,1.,1.5;mmin,mmax+flatmmin_mmax,1.,1.5 beta+flat,-4.,12.;alpha+flat,-12.,4. mmin,mmax+flatmmin_mmax,1.,1.5;alpha+flat,-12.,4. mmin,mmax+flatmmin_mmax,1.,1.5 beta+flat,-4.,12.;mmin,mmax,mu1,mu2+flatmminmu1mu2_mmax,1.,1.5,1.,3.,1.,3. sigma1+flat,0.01,2. sigma2+flat,0.01,2. w+flat,0.,1.;mmin,mmax,mu1,mu2+flatmminmu1mu2_mmax,1.,1.5,1.,3.,1.,3. sigma1+flat,0.01,2. sigma2+flat,0.01,2. w+flat,0.,1. beta+flat,-4.,12."
NUMPARAMS="2,2,3,3,7,7" # excluding beta
WALKERS="10,21,21,36,105,136"

NSBHPOPMODELS="unif_m1_unif_m2_qpair,unif_m1_unif_m2_qpair,unif_m1_power_m2_qpair,unif_m1_power_m2_qpair,unif_m1_bimodcut_m2_qpair,unif_m1_bimodcut_m2_qpair"

SELECTS="semianalyticvt,chirpmass52"

NUMLIKE=1000
NUMSEL=5000
NUMBURN=1000
NUMPOST=10000

IFS=';' read -r -a likes <<< "$LIKES"
IFS=';' read -r -a classes <<< "$CLASSES"
IFS=',' read -r -a likesets <<< "$LIKESETS"
IFS=',' read -r -a minmmaxs <<< "$MINMMAXS"
IFS=',' read -r -a popmodels <<< "$POPMODELS"
IFS=';' read -r -a popstarts <<< "$POPSTARTS"
IFS=';' read -r -a poppriors <<< "$POPPRIORS"
IFS=',' read -r -a numparams <<< "$NUMPARAMS"
IFS=',' read -r -a walkers <<< "$WALKERS"
IFS=',' read -r -a nsbhpopmodels <<< "$NSBHPOPMODELS"
IFS=',' read -r -a selects <<< "$SELECTS"

i=0
for like in "${likes[@]}"
do
	IFS=',' read -r -a likelihoods <<< "$like"
	IFS=',' read -r -a classifications <<< "${classes[$i]}"
	likeset=${likesets[$i]}
	minmmax=${minmmaxs[$i]}
	
	j=0
	for popmodel in "${popmodels[@]}"
	do
	
		walker=${walkers[$j]}
		popstart=${popstarts[$j]}
		popprior=${poppriors[$j]}
		numparam=${numparams[$j]}
		nsbhpopmodel=${nsbhpopmodels[$j]}
	
		for select in "${selects[@]}"
		do
	
			mkdir "$PWD/set${likeset}-${popmodel}-${select}"
			echo "sample-pop-params ${popmodel} -n 10000 -p ${popstart} -F False -g 100000 -o $PWD/set${likeset}-${popmodel}-${select}/${popmodel}_prior.csv -v" > "$PWD/set${likeset}-${popmodel}-${select}/doit"
			echo "" >> "$PWD/set${likeset}-${popmodel}-${select}/doit"
			echo "head -n 1 $PWD/set${likeset}-${popmodel}-${select}/${popmodel}_prior.csv > $PWD/set${likeset}-${popmodel}-${select}/${popmodel}_prior.csv.tmp
			awk '{FS= \",\"} \$${numparam} > ${minmmax} {print \$0}' $PWD/set${likeset}-${popmodel}-${select}/${popmodel}_prior.csv >> $PWD/set${likeset}-${popmodel}-${select}/${popmodel}_prior.csv.tmp
			head -n $((${walker}+1)) $PWD/set${likeset}-${popmodel}-${select}/${popmodel}_prior.csv.tmp > $PWD/set${likeset}-${popmodel}-${select}/${popmodel}_prior.csv
			rm $PWD/set${likeset}-${popmodel}-${select}/${popmodel}_prior.csv.tmp" >> "$PWD/set${likeset}-${popmodel}-${select}/doit"
			echo "" >> "$PWD/set${likeset}-${popmodel}-${select}/doit"
			echo "infer-pop-params $PWD/set${likeset}-${popmodel}-${select}/${popmodel}_prior.csv $(for likelihood in "${likelihoods[@]}"; do echo -n "${LIKEPATH}/${likelihood} "; done) -p ${popmodel} ${nsbhpopmodel} -C $(for class in "${classifications[@]}"; do echo -n "${class} "; done) -c m1_source m2_source dL z likelihood -l ${NUMLIKE} -P ${popprior} -F False -D quad,0.,1000. -B 3. 60. ${NSBHBETA} -f ${select} -S 1.,60.,1.,3.,0.,1000. -s ${NUMSEL} -t ${NUMPOST} -w ${walker} -b ${NUMBURN} -o $PWD/set${likeset}-${popmodel}-${select}/${popmodel}.csv --diag -v" >> "$PWD/set${likeset}-${popmodel}-${select}/doit"
			echo "" >> "$PWD/set${likeset}-${popmodel}-${select}/doit"
			echo "build-ppd $PWD/set${likeset}-${popmodel}-${select}/${popmodel}.csv -p ${popmodel} -s ${NUMSEL} -f ${select} -o $PWD/set${likeset}-${popmodel}-${select}/${popmodel}_ppd.csv -t med -v" >> "$PWD/set${likeset}-${popmodel}-${select}/doit"

			nohup bash "$PWD/set${likeset}-${popmodel}-${select}/doit" 1> "$PWD/set${likeset}-${popmodel}-${select}/nohup.out" 2> "$PWD/set${likeset}-${popmodel}-${select}/nohup.err" &
		
		done
		
		j=$(($j+1))
	done

	i=$(($i+1))
done
